# Generated by Django 5.0.3 on 2024-04-08 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('completeName', models.CharField(max_length=100)),
                ('updateTime', models.CharField(max_length=100)),
                ('typeOfLimit', models.CharField(choices=[('static', 'Estático'), ('dinamic', 'Dinâmico')], max_length=30)),
                ('upperLimitStatic', models.FloatField()),
                ('lowerLimitStatic', models.FloatField()),
                ('basePrice', models.CharField(choices=[('ltp', 'Last Traded Price (LTP)'), ('c_last', 'C-LAST'), ('most_recent', 'Most Recent')], max_length=30)),
                ('upperLimitDinamic', models.FloatField()),
                ('lowerLimitDinamic', models.FloatField()),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
