# Generated by Django 5.0.3 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitor',
            name='basePrice',
            field=models.CharField(blank=True, choices=[('ltp', 'Last Traded Price (LTP)'), ('c_last', 'C-LAST'), ('most_recent', 'Most Recent')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitDinamic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitStatic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitDinamic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitStatic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
