# Generated by Django 5.0.3 on 2024-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_stockmonitor_baseprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitor',
            name='updateTime',
            field=models.CharField(choices=[('1min', '1min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min')], max_length=100),
        ),
    ]
