# Generated by Django 5.0.3 on 2024-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_stockmonitor_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitor',
            name='basePrice',
            field=models.CharField(choices=[('ltp', 'Last Traded Price (LTP)'), ('c_last', 'C-LAST'), ('most_recent', 'Most Recent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitDinamic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitStatic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitDinamic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitStatic',
            field=models.FloatField(),
        ),
    ]
