# Generated by Django 5.0.3 on 2024-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_stockmonitor_baseprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitDinamic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='lowerLimitStatic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitDinamic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='upperLimitStatic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
