# Generated by Django 5.0.3 on 2024-04-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_stockmonitor_lowerlimitdinamic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitor',
            name='basePrice',
            field=models.CharField(blank=True, choices=[('ltp', 'Last Traded Price (LTP)'), ('c_last', 'C-LAST'), ('most_recent', 'Most Recent')], max_length=30, null=True),
        ),
    ]
